{% set name = "sos-sas" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd81c5102afdc511ba98a9fd6ef1f535e5f127674e28e160bb993920de1a1949

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - sos-notebook >=0.19.4
    - sas_kernel
    - saspy
    - sas7bdat
    - python >=3.6

test:
  imports:
    - sos_sas

about:
  home: https://github.com/vatlab/sos-sas
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for SAS
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-sas

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
