schema_version: 1

context:
  version: "0.20.1"

package:
  name: sos-sas
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sos-sas/sos_sas-${{ version }}.tar.gz
  sha256: 63c7380c157e63ff348b583c7309df25b9efab478661a1272886c82ac4edc194

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - sos-notebook >=0.19.4
    - sas_kernel
    - saspy
    - sas7bdat
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - sos_sas
      pip_check: true
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SoS language module for SAS
  homepage: https://github.com/vatlab/sos-sas
  repository: https://github.com/vatlab/sos-sas
  documentation: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
